spring:
  datasource:
    dynamic:
      primary: data
      strict: true
      datasource:
        config:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/pay_settle?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: 123456
        data:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/pay_settle?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: 123456
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 3000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data-mysql.sql
      encoding: UTF-8

pay:
  shard:
    enabled: false
  db:
    init:
      enabled: true
